version: "3.9"
services:

    api:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        ports:
            - "8081:80"

    api-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./api:/app
        environment:
            PHP_IDE_CONFIG: serverName=API

    api-php-cli1:
        build:
            context: docker
            dockerfile: development/php-cli1/Dockerfile
        volumes:
            - ./api:/app

    database:
        image: mysql:8.0.27
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql
